# Generated by Django 5.2.13 on 2026-05-03 15:09

import apps.orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_tablelocation_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_code', models.CharField(default=apps.orders.models.generate_order_code, max_length=10, unique=True)),
                ('order_status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Ready', 'Ready'), ('Served', 'Served'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='New', max_length=20)),
                ('payment_method', models.CharField(choices=[('eSewa', 'eSewa'), ('Khalti', 'Khalti'), ('COD', 'Cash on Delivery')], default='COD', max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_response', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='menu.table')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kot_status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Prepared', 'Prepared')], default='Pending', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
