# Generated by Django 5.2.14 on 2026-05-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
