# Generated by Django 5.2.13 on 2026-04-30 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0002_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Author Language',
                'verbose_name_plural': 'Author Languages',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('waiter', 'Waiter'), ('owner', 'Owner'), ('cashier', 'Cashier')], default='admin', max_length=20),
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(default='')),
                ('avatar', models.ImageField(null=True, upload_to='authors/')),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorNameTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_name_translations', to='autho.authorlanguage')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_translations', to='autho.authorprofile')),
            ],
            options={
                'verbose_name': 'Author Name',
                'verbose_name_plural': 'Author Names',
                'indexes': [models.Index(fields=['author', 'lang'], name='autho_autho_author__f8b787_idx')],
                'unique_together': {('author', 'lang')},
            },
        ),
    ]
