# Generated by Django 5.2.14 on 2026-05-13 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("autho", "0003_authorlanguage_alter_user_role_authorprofile_and_more"),
    ]

    operations = [
        # 1. Clear the constraint FIRST, while both fields still exist
        migrations.AlterUniqueTogether(
            name="authornametranslation",
            unique_together=set(),
        ),
        # 2. Now it's safe to remove the fields
        migrations.RemoveField(
            model_name="authornametranslation",
            name="lang",
        ),
        migrations.RemoveField(
            model_name="authornametranslation",
            name="author",
        ),
        # 3. Delete the models last
        migrations.DeleteModel(
            name="AuthorLanguage",
        ),
        migrations.DeleteModel(
            name="AuthorNameTranslation",
        ),
    ]
